#
# Copyright (C) 2021- mareel.io <admin@empo.im>
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=mareel-connector
PKG_VERSION:=0.0.1
PKG_RELEASE:=1

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/Mareel-io/core.git
PKG_SOURCE_VERSION:=master

include $(INCLUDE_DIR)/package.mk

define Package/mareel-connector
  SECTION:=mareel
  CATEGORY:=mareel
  TITLE:=Mareel Connector Daemon
  URL:=https://mareel.io
endef

define Package/mareel-connector/description
  Mareel Connector Daemon
endef

define Build/Configure
endef

define Build/Compile
endef

define Build/Install
endef

define Build/Clean
endef

$(eval $(call BuildPackage,bridge))
