#!/bin/sh

FLAGFILE=/etc/.mareel-restore-flag

if [ ! -d "/mnt/ota_backup" ]; then
    exit 0;
fi

if [ ! -f "${FLAGFILE}" ]; then
    echo "Restoring backup..."
    rm -rf /etc/config/*
    cp -arv /mnt/ota_backup/* /etc/config/
    touch "${FLAGFILE}"
    reboot
fi
